version: '3.8'

services:
  neo4j:
    image: neo4j:5.8
    container_name: neo4j-cti
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./data:/data
      - ./import:/import
      - ./logs:/logs

